<?php include_once('header.php') ?>

<div class="section section-policy">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Terms &amp; Conditions</h1>
				<p>E-Safe repairs provide this service contract for you. E-Safe repairs provide repairs required to your home electrics and appliance(s). This Service Contract will not be in force unless you have paid all amounts due to us. The Service Contract contains details of the services you have chosen and what is excluded from those services. No claims may be made within the first 30 days of the commencement of the plan. All appliance(s) must be in good working order, with no pre-existing faults, at the outset of the plan.</p>
				<br>
				<h3>DEFINITIONS</h3>
				<p>Service contract: the documentation sent to you regarding this plan which forms the contract of service between E-Safe repairs and the customer. You/your: the person named on your service contract. We/us/our: E-Safe repairs. Systems: Electrical/wiring within the property</p>
				<br>
				<h3>YOUR SERVICE CONTRACT</h3>
				<p>This Service Contract is not classified as an insurance product and therefore insurance regulations do not apply, however it is governed by UK laws and regulations concerning Service Contracts. This Service Contract is designed to offer you peace of mind against unexpected expenses arising from repairs required to your systems /appliance(s).  Please read this Service Contract carefully and make sure you understand it fully and are willing to comply with its terms and conditions in order that you can achieve maximum benefit from it. We will always be fair and reasonable in our operation of the scheme, however failure to comply with the terms and conditions may jeopardize the payment of any repairs and could lead to your Service Contract becoming void. Your home electrics and appliance(s) covered by this plan must be in good working order at the start of this plan and located at the address provided to us.</p>
				<br>
				<h3>MAINTAINING PROTECTION UNDER YOUR PLAN</h3>
				<p>Your Plan may be paid for on a monthly, quarterly or annual basis via Direct Debit. We will collect your fee for this Plan by Direct Debit from your chosen bank account on an agreed date each month or quarter and, subject to the successful collection of that monthly or quarterly fee, we will provide the ‘repair service’ detailed in this Plan for the month or quarter in which the monthly or quarterly fee has been collected. This Plan commences on the date shown on your Service Contract and continues for a minimum 12 month period and then continues on a rolling basis until such times as you wish to cancel it. Should you fail to make a payment in any month or quarter, we will attempt to contact you to discuss this, should we not be able to contact you, your Plan will cease with immediate effect.</p>
				<br>
				<h3>REQUESTING/REPORTING A REPAIR</h3>
				<p>If you experience a fault with your system/appliance(s) and repairs are required, please call our customer service helpline (INSERT TELEPHONE) as soon as possible. Our lines are open Monday to Friday 9am-5.00pm (excluding Bank Holidays). You will need to provide all information, including the nature of the fault, at the time of the call. The plan will only cover electrics and appliance(s) within the confines of your property..</p>
				<br>
				<h3>WHAT HAPPENS NEXT</h3>
				<p>Our Customer Service Team will source an engineer local to you to make direct contact with you to arrange an appointment at a mutually convenient time to inspect the reported fault. Appointments will be carried out within the repairer’s normal working hours. Only engineers approved by us are authorised to carry out repairs under this plan, unless we agree otherwise in advance. If we approve a repair but are unable to find an approved engineer, we may authorise you to use your own chosen repairer. You will have to pay them directly and claim the cost back from us. Make sure you keep a copy of their invoice to send to us. Your contract allows for a maximum of £500 per claim, per year. Unless all the terms of the above are complied with, we reserve the right to cancel the Plan.</p>
				<br>
				<h3>YOUR OBLIGATIONS AND CONDITIONS</h3>
				<p>Any information that we request when you apply for the plan must be provided. All information you give must not be false or misleading; Your system/appliance(s) must have been installed, maintained and operated/used in accordance with the manufacturer’s instructions where applicable. Your system/ appliance(s) must be in a residential dwelling at the address you informed us of. We will not be liable to repair the system/ appliance(s) under this Service Contract unless you have duly complied with all the terms and conditions contained in this Plan. The property where the fault has occurred must be used only for domestic purposes and owned by you. If you have opted to include any appliance(s) in your plan, they must be in good working order at the commencement of the plan, be readily accessible and meet all relevant safety standards. Should there be any work required to make your appliance(s) accessible for repair then this shall be your responsibility to arrange prior to requesting services from us. When requesting a repair from us under your plan you must inform us at the outset of any intended works required in order to make the repair accessible/compliant with all relevant safety standards and we shall be entitled to request certification of completed accessibility/compliance works prior to undertaking our repairs to your appliance(s). You must take reasonable steps to limit the damage to your property or appliance(s) in the event of a repair taking place.</p>
				<br>
				<h3>COOLING OFF PERIOD/CANCELLATION</h3>
				<p>There is a 14 day Cooling off period from the date of commencement of the Plan. Should you wish to cancel your Plan within this period, please call our Customer Service Team and we will refund any monies paid. If you wish to cancel your Plan after the Cooling off period, please contact our Customer Service Team on (INSERT TELEPHONE) and we will refund any monies paid on a pro rata basis, cancellations made after the 14 day cooling off period will also be subject to a £25 administration fee which will be deducted from any refund due. If you pay by Direct Debit, your next monthly or quarterly and any subsequent payments will not be collected, and the Plan will be cancelled. If you choose to cancel your Plan within 12 months of the commencement of the plan and a repair has been carried out, no refund will be given, and you will be required to repay the full cost of the repair.</p>
				<br>
				<h3>EXCLUSIONS</h3>
				<p>This Service Contract does not cover any event occurring because of Intentional acts, wilful neglect or the imposition of any abnormal conditions on the system.  You are expected to take all reasonable precautions when using the system. Inherent defects, wear and tear, etc. damage to or destruction of the system caused by: its own defective design materials or workmanship, a latent defect or defects, gradual deterioration, wear and tear, corrosion, rust, condensation or evaporation, dampness, dryness, dust, change in temperature and foreign objects; faulty or defective workmanship. War Risk and Terrorism: An event occurring as a result of war, invasion, acts of foreign enemies, hostilities (whether war is declared or not), civil war, rebellion, revolution, insurrection, military or usurped power, confiscation, nationalism or requisition or destruction or damage to property by or under the order of any government or public or legal authority; damage or destruction caused by, contributing to, or arising from an act of terrorism.</p>
				<p>Nuclear risk and Sonic Boom Damage or destruction caused by, contributed to or arising from: Ionizing radiation or contamination by radioactivity from any nuclear fuel or from any nuclear waste from the combustion of nuclear fuel, the radioactive, toxic, explosive or other hazardous properties of any explosive nuclear assembly or component thereof, Pressure waves caused by aircraft or other aerial devices traveling at sonic or supersonic speeds</p>
				<p>Consequential loss: Any consequential loss or damage arising from the event or from any cause whatsoever. Consequential loss shall include, but not be limited to, any financial loss or the cost of business interruption arising from the loss of use of the system/ appliance(s) and any liability to any third party for delay or non-performance of any contract with the third party. Consequential loss shall also include loss of use of any item of product (not itself subject to an event) due to its incompatibility with any item of system repaired or replaced pursuant to this Service Agreement.</p>
				<p><b>This Service Contract does not cover your appliance(s) unless you have taken out the additional cover for this in which case the following exclusions will also apply:</b> Damage during delivery, installation or transportation of the appliance(s) by a third party who is not our agent; Any breakdown cost already covered by any manufacturer, supplier or repairer guarantee or warranty on the appliance(s); Replacement or recall of the appliance(s) (or any part) by a supplier or the manufacturer; Modifying or making the appliance(s) comply with legislation, work on the appliance(s) that is only required due to legislation changes or making it safely accessible; Normal operation or adjustment of the product controls, cosmetic damage such as damage to paintwork, dents or scratches.</p>
				<p><b>The following are not covered by the Plan:</b></p>
				<p>Repairer costs and charges where a fault cannot be found with the system/ appliance(s). A system/ appliance(s) that does not meet the current regulations in force at the time of purchase or faults relating to the installation of the system/ appliance(s); which relates to  routine maintenance of the system, supplies or service in your home; Repair requests arising from the interruption, failure or disconnection of public services to your home (including water, electricity or gas supply) however caused or from gas leaks; Total loss of use of the system/ appliance(s) due solely to the non-availability of replacement or substitute parts. We do not cover against flood damage.</p>
				<br>
				<h3>PAYMENT OF YOUR FEE</h3>
				<p>Your service contract is based on an annual plan, which may be paid on a monthly or quarterly basis via Direct Debit. You must make regular payments as agreed. If we are unable to collect a payment from your bank on the date agreed, we may attempt to take payment again unless you advise us otherwise. If we are unable to collect any payment which is due, your service contract will be suspended and you will not be able to make use of the service contract until all outstanding monies have been received. You may cancel the plan at any time however should you make a claim within the first year of your plan you will be required to pay for a minimum of a year or refund the value of any claim amount paid to you. After the first year, your plan will continue on a rolling monthly/quarterly/annually basis until such times as you wish to cancel the plan. We may use a collection agency to recover any amount owing to us.</p>
				<br>
				<h3>FRAUD</h3>
				<p>You must not act in a fraudulent manner. If you, or anyone acting for you, requests a repair under the Plan knowing it to be false or fraudulently exaggerated in any respect, or makes a statement in support of a repair request knowing the statement to be false in any respect, or submits a document in support of a repair request knowing the document to be forged or false in any respect, or makes a repair request in respect of any loss or damage known by you to be as a result of a wilful act or with your connivance, then we will be entitled to recover the amount paid under the Plan relating to the specific declared appliance(s) since inception and may inform the police of the circumstances.</p>
				<br>
				<h3>COMPLAINT</h3>
				<p>If you are unhappy with the service provided and wish to make a complaint, please contact our Customer Service Team via telephone (INSERT TELEPHONE) or you may email us at (INSERT EMAIL) We aim to respond to all correspondence within 24 working hours.</p>
				<br>
				<h3>DATA PROTECTION</h3>
				<p>E-Safe Repairs will use the information supplied by you to maintain the Plan requested; for administration purposes including the recovery of any monies owed to us; and to arrange repairs to your system. We may also use your information to contact you further to inform you of any new products or offers which we feel may be of interest to you unless you have asked us not to. You as a customer have the right to be informed, the right of access, the right to rectification, the right to erasure, the right to restrict processing, the right to data portability, the right to object, rights in relation to automated decision making and profiling of the data we hold of you. For more information about what information we hold, please contact the data protection officer via writing using the details provided under “company Information”.</p>
			</div>
		</div>
	</div>
</div>

<?php include_once('footer.php') ?>